basePath: /api
definitions:
  models.Class:
    properties:
      class_name:
        type: string
      id:
        type: integer
      student_count:
        type: integer
    type: object
  models.Student:
    properties:
      class_id:
        type: integer
      id:
        type: integer
      student_name:
        type: string
      student_section:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: This is a sample school API server.
  title: School API
  version: "1.0"
paths:
  /classes:
    get:
      description: Get a list of all classes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Class'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all classes
      tags:
      - classes
    post:
      consumes:
      - application/json
      description: Create a new class with the provided details
      parameters:
      - description: Class object to create
        in: body
        name: class
        required: true
        schema:
          $ref: '#/definitions/models.Class'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Class'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new class
      tags:
      - classes
  /classes/{id}:
    delete:
      description: Delete a specific class by its ID
      parameters:
      - description: Class ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete a class
      tags:
      - classes
    get:
      description: Get a specific class by its ID
      parameters:
      - description: Class ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Class'
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Class not found
          schema:
            type: string
      summary: Get a class by ID
      tags:
      - classes
    put:
      consumes:
      - application/json
      description: Update an existing class with the provided details
      parameters:
      - description: Class ID
        in: path
        name: id
        required: true
        type: integer
      - description: Class object to update
        in: body
        name: class
        required: true
        schema:
          $ref: '#/definitions/models.Class'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Class'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update a class
      tags:
      - classes
  /students:
    get:
      description: Get a list of all students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Student'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all students
      tags:
      - students
    post:
      consumes:
      - application/json
      description: Create a new student with the provided details
      parameters:
      - description: Student object to create
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/models.Student'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Student'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new student
      tags:
      - students
  /students/{id}:
    delete:
      description: Delete a specific student by its ID
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete a student
      tags:
      - students
    get:
      description: Get a specific student by its ID
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Student not found
          schema:
            type: string
      summary: Get a student by ID
      tags:
      - students
    put:
      consumes:
      - application/json
      description: Update an existing student with the provided details
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      - description: Student object to update
        in: body
        name: student
        required: true
        schema:
          $ref: '#/definitions/models.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update a student
      tags:
      - students
swagger: "2.0"
